### ISSUE TITLE
Migrate pdxruby.org pages

### ISSUE THREAD

**Issue by paulbaker3** [pdxruby/pdxruby.github.io#1]
Not sure how we want to organize this. Perhaps a checklist of the existing pages and we can associate PRs to those?

- [ ] /index
- [ ] /present
- [ ] /job_guidelines
- [ ] /codeofconduct
- [ ] /wikijoke
- [ ] /learn
- [ ] /past-meetings
- [ ] /history
- [ ] /statistics

**Comment by jc00ke** [comment]
Sure, that works for me. If we don't like it we can change it. Or an issue per page... you decide :wink:
