### ISSUE TITLE
support editing in github editor as well as prose

### ISSUE THREAD

**Issue by edrex** [pdxruby/pdxruby.github.io#19]
It's more familiar for most people, and is simpler since it doesn't have CMS-type features. Let's support both!

https://github.com/pdxruby/pdxruby.github.io/edit/master/index.md
https://github.com/pdxruby/pdxruby.github.io/new/master/foo/?filename=baz.md

**Comment by jc00ke** [comment]
Heh, was wondering about that. Saw it in the settings but haven't played with it yet. Neat!
