### ISSUE TITLE
Flip DNS

### ISSUE THREAD

**Issue by edrex** [pdxruby/pdxruby.github.io#22]
Update pdxruby.org DNS to point to gh-pages.

 - [ ] Add file /CNAME containing `pdxruby.org`.
 - [ ] Add CNAME record `pdxruby.org: pdxruby.github.io`.
 - [ ] Remove existing record.

**Comment by edrex** [comment]
@jc00ke anything more you want to do before switching it over?

**Comment by jc00ke** [comment]
It would be good to get some more eyes on it, @geeksam and @kcomandich? @shawnacscott?

**Comment by kcomandich** [comment]
Looks great so far! I'll take a closer look tomorrow.
I've set the TTL to 5min, and can update the DNS as soon as we're ready.

**Comment by jc00ke** [comment]
Flipped!

**Comment by edrex** [comment]
Now I feel a rush to get the look and feel dialed in before next month's meetup and traffic. Are there any analytics data for the old site? Do we want to set up some analytics for this one?
