### ISSUE TITLE
Logo distorts on narrow view ports

### ISSUE THREAD

**Issue by edrex** [pdxruby/pdxruby.github.io#27]

**Comment by edrex** [comment]
related: #28

**Comment by jc00ke** [comment]
@edrex is this still a valid open issue? If not, let's close it up :tada:

**Comment by edrex** [comment]
C'mon, at least include a screenshot 2016 Eric!

IDK, there is a little horizontal scrunching when the viewport gets real narrow but maybe that's by design. seems pretty nitpicky. :shrug:
