### ISSUE TITLE
Serve over SSL

### ISSUE THREAD

**Issue by jc00ke** [pdxruby/pdxruby.github.io#30]
Would be great to front this with Cloudflare or some other service that would force `https`

https://developer.ubuntu.com/en/blog/2016/02/17/how-host-your-static-site-https-github-pages-and-cloudflare/

**Comment by reidab** [comment]
I recently set up Cloudflare on a couple of other static sites — I'll take this on.

**Comment by reidab** [comment]
🔏✅

**Comment by jc00ke** [comment]
Thanks @reidab!
