### ISSUE TITLE
pdxruby.org domain

### ISSUE THREAD

**Issue by reidab** [pdxruby/pdxruby.github.io#66]
Hello!

Stumptown Syndicate currently holds the domain registration for pdxruby.org, but none of the pdxruby folks who used to be on the board there (me, @kcomandich, @aeschright) are still on the board. The domain expires in 60 days and it probably makes sense to transfer that registration to someone who's still actively involved in managing the site. 

Is there a consensus on who that might be?

(I'm willing to be that person if nobody else is, if we can get sponsorship/contributions to cover the renewals.)

**Comment by jc00ke** [comment]
I'm already managing/covering costs for Meetup, and I tend to merge most of the PRs to this site, so I'll volunteer. I can manage contributions to cover the costs. Our community is great at that; very giving!

**Comment by rmkubik** [comment]
Hi @jc00ke, I'm a new member of the Stumptown Syndicate board. Can I work with you to transfer over ownership of the domain?

**Comment by jc00ke** [comment]
@rmkubik sure, we probably need to do it quickly before it expires huh?

**Comment by rmkubik** [comment]
@jc00ke Yeah! Is there an email, slack, or twitter that we can organize the transfer on?

**Comment by jc00ke** [comment]
@rmkubik there's the [pdxruby Slack](http://pdxruby.slack.com/) or you can hit me up on [Keybase](https://keybase.io/jc00ke) for chat, otherwise email is fine: <my first name>@relativepath dot io

**Comment by jc00ke** [comment]
![domains](https://user-images.githubusercontent.com/18191/58287052-f3ae5180-7d64-11e9-97a8-4e13b7224fcb.png)
![My Precious](https://media.giphy.com/media/3oFyCVxsQn6RBa0r5u/giphy.gif)
