### ISSUE TITLE
Who else should have access to manage DNS?

### ISSUE THREAD

**Issue by jc00ke** [pdxruby/pdxruby.github.io#70]
Right now it's just me in a `pdxruby` organization on Gandi. That's a `bus factor < 2`, so who else should have access? @reidab @geeksam @aeschright? Anyone else?

**Comment by geeksam** [comment]
I don't mind at least having access, but I'd be extremely reluctant to actually touch anything :)

**Comment by jc00ke** [comment]
I just sent an admin invitation @geeksam

**Comment by kcomandich** [comment]
I can be a backup.

**Comment by jc00ke** [comment]
:bus: :boom: mitigated by @geeksam and @kcomandich
